name: Lua
on:
  pull_request:
    branches:
      - main
jobs:
  lua_lint:
    name: Lint Lua 💅
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: --globals vim --no-max-line-length -- .
  lua_format:
    name: Formatting Lua 💅
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Action
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
